export default [
    {
      path:'/oeeValue',
      models:()=>[],
      component:()=>import('../modules/oeeValue/index.v')
    },
    {
      path:'/message',
      models:()=>[import('../modules/message/deviceAlertList.m')],
      component:()=>import('../modules/message/index.v')
    },
    
    {
      path:'/my',
      models:()=>[],
      component:()=>import('../modules/my/index.v')
    },
    {
      path:'/deviceAlert',
      models:()=>[import('../modules/deviceAlertList/deviceAlert/index.m')],
      component:()=>import('../modules/deviceAlertList/deviceAlert/index.v')
    },
    {
      path:'/deviceAlert/fixlog',
      models:()=>[import('../modules/deviceAlertList/deviceAlert/index.m')],
      component:()=>import('../modules/deviceAlertList/deviceAlert/fixlog/index.v')
    },
    {
      path:'/deviceAlert/history',
      models:()=>[import('../modules/deviceAlertList/deviceAlert/index.m')],
      component:()=>import('../modules/deviceAlertList/deviceAlert/history/index.v')
    },
    {
      path:'/deviceAlert/spStore',
      models:()=>[import('../modules/deviceAlertList/deviceAlert/index.m')],
      component:()=>import('../modules/deviceAlertList/deviceAlert/spStore/index.v')
    },
    {
      path:'/deviceAlert/faq',
      models:()=>[import('../modules/deviceAlertList/deviceAlert/index.m')],
      component:()=>import('../modules/deviceAlertList/deviceAlert/faq/index.v')
    },
    {
      path:'/deviceFixList',
      models:()=>[import('../modules/deviceFixList/index.m')],
      component:()=>import('../modules/deviceFixList/index.v')
    },
    {
      path:'/deviceFix',
      models:()=>[],
      component:()=>import('../modules/deviceFixList/deviceFix/index.v')
    },
    {
      path:'/deviceMaintenanceList',
      models:()=>[import('../modules/deviceMaintenanceList/index.m')],
      component:()=>import('../modules/deviceMaintenanceList/index.v')
    },
    {
      path:'/deviceMaintenance',
      models:()=>[import('../modules/deviceMaintenanceList/deviceMaintenance/index.m')],
      component:()=>import('../modules/deviceMaintenanceList/deviceMaintenance/index.v')
    },
    {
      path:'/energyAnalysisList',
      models:()=>[import('../modules/energyAnalysisList/index.m')],
      component:()=>import('../modules/energyAnalysisList/index.v')
    },
    {
      path:'/energyAnalysis',
      models:()=>[],
      component:()=>import('../modules/energyAnalysisList/energyAnalysis/index.v')
    },
    {
      path:'/deviceList',
      models:()=>[import('../modules/deviceList/index.m')],
      component:()=>import('../modules/deviceList/index.v')
    },
    {
      path:'/deviceStatus',
      models:()=>[import('../modules/deviceList/deviceStatus/index.m')],
      component:()=>import('../modules/deviceList/deviceStatus/index.v')
    },     

    {
      path:'/',
      models:()=>[],
      component:()=>import('../modules/home/index.v')
    },

];
